name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "feature/*"

env:
  MONGO_URI: "mongodb://${{vars.MONGO_USERNAME}}:${{secrets.MONGO_PASSWORD}}@10.10.0.61:8635,10.10.0.197:8635/test?authSource=admin"
jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        operating_system: [ubuntu-latest, windows-latest]
        node_version: [18, 19, 20]
        exclude:
          - operating_system: windows-latest
            node_version: 18

    runs-on: ${{ matrix.operating_system }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS Version - ${{matrix.node_version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node_version}}

      - name: Install Dependencies
        run: npm install

      - name: Unit Testing
        run: npm test

      - name: Archive Test Result
        uses: actions/upload-artifact@v3
        with:
          name: Mocha-Test-Result
          path: test-results.xml
